const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const render = require('../docs/publications.js');
const papers = JSON.parse(fs.readFileSync(path.join(__dirname, '../docs/content.json'), 'utf8')).journal;
const original = JSON.stringify(papers);
const fixture = {title: 'New paper <test>', authors: 'Test Author', venue: "Test journal, Editor's Choice", year: '2027', news_date: '2026-09-29', links: [], url: 'https://example.org/paper'};
// An added year wins even if an editor appends the record; both views use it.
const olderPapers = papers.map(p => ({...p, news_date: '2025-01', news_added_at: undefined}));
const changed = [...olderPapers, fixture];
const recent = render.recent(changed);
const journal = render.journal(changed);
assert.equal((recent.match(/<article /g) || []).length, 3);
assert.ok(recent.startsWith('<article class="news-item">'));
assert.ok(recent.includes('<strong>New paper &lt;test&gt;</strong>'));
assert.ok(journal.includes(render.publication(fixture)));
assert.ok(recent.includes('<time datetime="2026-09-29">Sep. 2026</time>'));
assert.ok(recent.includes('is accepted to <strong>Test journal</strong>.'));
assert.ok(render.news({...fixture, news_date: undefined}).includes('News date not provided'));
assert.ok(!render.news({...fixture, news_date: undefined}).includes('<time'));
assert.ok(render.publication(fixture).includes('publication-distinction'));
assert.equal(render.ordered([{...fixture, title:'First'}, {...fixture, title:'Second'}])[0].title, 'First');
assert.ok(!render.publication({...fixture, url:'javascript:alert(1)'}).includes('href='));
assert.equal(JSON.stringify(papers), original);
assert.equal((render.journal(papers).match(/class="publication-link"/g)||[]).length, papers.filter(p=>p.url).length);
console.log('PASS: additions update both views, latest three, stable ordering, links, escaping and distinctions.');

const newlyRegistered = {...fixture, title: 'Newly registered older-year paper', year: '2020', news_date: '2026-10', news_added_at: '2026-10-01T01:00:00+09:00'};
const registrationNews = render.recent([...olderPapers, newlyRegistered]);
assert.ok(registrationNews.includes('Oct. 2026'));
assert.ok(registrationNews.indexOf(newlyRegistered.title) < registrationNews.indexOf(papers[0].title));
assert.equal((registrationNews.match(/class="news-item"/g)||[]).length, 3);
console.log('PASS: registration order controls recent news.');
